import logging
import json
import random
import collections
import os
import asyncio
from typing import Optional, List, Dict, Any
from runtime.gincana_engine import GincanaEngine
from runtime.warfare_engine import WarfareEngine
from runtime.economy_engine import EconomyEngine
from runtime.gangwar_engine import GangWarEngine

logger = logging.getLogger("BBB_IA")

class World:
    # Modos de jogo válidos e tamanho recomendado por modo
    MODE_SIZES = {
        "survival": 32,
        "gincana":  32,
        "warfare":  40,
        "economy":  36,
        "gangwar":  40,
        "hybrid":   44,
    }
    VALID_MODES = set(MODE_SIZES.keys())

    def __init__(self, size=None, game_mode: str = "survival"):
        # Modo de jogo
        self.game_mode: str = game_mode if game_mode in self.VALID_MODES else "survival"
        # Initialize world state with grid size
        self.size = self._resolve_world_size(size)
        self._configure_landmarks()
        self.ticks = 0
        self.started = False # T14: Game only ticks when started
        self.game_over = False
        self.winner = None
        self.entities: Dict[str, Any] = {} # Map of id -> entity (agents, items)
        self.system_agent_overrides: Dict[str, str] = {} # sys_id -> profile_id
        
        # Initialize map with basic resources
        self._init_map()
        
        # the agents list to tick
        self.agents = []
        self.ai_interval = 5 # Default interval for AI decisions
        self.spawn_index = 0
        self.game_over_tick = None
        self.pending_spawns = [] # List of (spawn_tick, agent_obj)
        self.agent_class = None
        self.extra_names = [
            ("Beto", "Beto é um lenhador forte. Ele foca em coletar madeira e pedra para construir coisas grandes."),
            ("Carla", "Carla é uma bióloga curiosa. Ela estuda as árvores e sempre sabe onde encontrar as melhores frutas."),
            ("Dudu", "Dudu é um explorador ágil. Ele gosta de percorrer o mapa inteiro e descobrir novos lugares."),
            ("Eva", "Eva é uma mística da ilha. Ela acredita que as árvores têm espírito e fala com as pedras."),
            ("Fabio", "Fabio é um atleta competitivo. Ele quer ser o mais forte e saudável da ilha."),
            ("Gabi", "Gabi é uma artista. Ela vê beleza na ilha e gosta de conversar sobre cores e paisagens.")
        ]
        self.history_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hall_of_fame.json")
        self.settings_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "world_settings.json")
        self.scores: Dict[str, Any] = {}
        self.hall_of_fame: List[Dict[str, Any]] = []
        self.ai_interval = 5
        self.player_count = 4
        # Preset auxiliar da UI. Perfis por agente continuam sendo a fonte de verdade.
        self.ai_provider = "omnirouter"
        self.ai_model = "kr/claude-sonnet-4.5"
        self.omniroute_url = "http://localhost:20128/v1"
        self.game_over_tick: Optional[int] = None
        self.ai_events: List[Dict[str, Any]] = [] # Queue for events generated by background AI tasks
        self.thinking_agents = set() # Set of agent IDs currently awaiting AI response
        self.ai_decider = None  # Optional async callback (agent, context, tick) -> action dict|None
        self.session_id: Optional[str] = None
        self.tournament_end_tick: Optional[int] = None
        self.active_tournament_id: Optional[str] = None

        # ── F04 — Eventos Dinâmicos da Ilha ──────────────────────────────────
        self.active_event: Optional[dict] = None    # {type, message, end_tick, effects}
        self.event_end_tick: int = 0
        self.event_history: List[dict] = []         # Histórico de eventos da sessão
        # Probabilidade por tick de disparar evento (ajustável)
        self.event_chance: float = 0.005            # ~0.5% por tick = ~1 evento a cada 200 ticks

        # ── F07 — Reputação Social ────────────────────────────────────────────
        # Rastreamento global de alianças para evitar duplicatas e decidir bônus
        self.alliance_bonus_hp_per_tick: float = 0.15  # HP extra por tick para aliados próximos
        self.betrayal_penalty: float = -20.0           # Delta de reputação por traição

        # ── F08 — Missões Individuais ─────────────────────────────────────────
        self.mission_catalog: List[dict] = []       # Preenchido em _init_missions()
        self._init_missions()

        # ── F12 — Modo Gincana ────────────────────────────────────────────────
        self.gincana: GincanaEngine = GincanaEngine(self)

        # ── F13-F16 — Modo Warfare ────────────────────────────────────────────
        self.warfare: WarfareEngine = WarfareEngine(self)

        # ── F10+F17+F18+F19 — Economia ───────────────────────────────────────
        self.economy: EconomyEngine = EconomyEngine(self)

        # ── F20 — Guerra de Gangues ──────────────────────────────────────────
        self.gangwar: GangWarEngine = GangWarEngine(self)

        # Day/Night Cycle: 120 ticks total (70 day + 10 dusk + 30 night + 10 dawn)
        self.DAY_CYCLE = 120
        self._was_night = False  # Track night transitions for zombie conversion
        self._load_history()


    def _resolve_world_size(self, size) -> int:
        if size is None:
            # Se tamanho não especificado, usar tamanho recomendado pelo modo
            env_size = os.getenv("WORLD_SIZE", "").strip()
            if env_size:
                try:
                    size = int(env_size)
                except ValueError:
                    logger.warning("Invalid WORLD_SIZE=%s. Using mode default.", env_size)
                    size = self.MODE_SIZES.get(self.game_mode, 32)
            else:
                size = self.MODE_SIZES.get(self.game_mode, 32)
        try:
            parsed = int(size)
        except (TypeError, ValueError):
            parsed = 32
        # Keep minimum safe size to preserve pathing landmarks and home spacing.
        return max(20, parsed)

    def _configure_landmarks(self) -> None:
        margin = max(2, min(4, self.size // 8))
        opposite = self.size - margin - 1
        if opposite <= margin:
            margin = 1
            opposite = self.size - 2

        self.house_positions = [
            (margin, margin),
            (opposite, opposite),
            (opposite, margin),
            (margin, opposite),
        ]
        self.house_by_name = {
            "João": self.house_positions[0],
            "Maria": self.house_positions[1],
            "Zeca": self.house_positions[2],
            "Elly": self.house_positions[3],
        }

        center = self.size // 2
        self.pond_center_x = center
        self.pond_center_y = center
        self.pond_radius = max(3, self.size // 8)
        self.pond_radius_sq = self.pond_radius ** 2
        self.tree_min_distance_sq = (self.pond_radius + 2) ** 2

        self.cemetery_x = max(3, self.size - 5)
        self.cemetery_y = max(3, self.size // 4)
        self.house_shelter_radius = 2

    def set_ai_decider(self, ai_decider) -> None:
        """Injecta um orquestrador de decisão (ex.: Thinker) para o loop de IA."""
        self.ai_decider = ai_decider

    def set_session_id(self, session_id: Optional[str]) -> None:
        """Atualiza o session_id atual para expor no world state."""
        self.session_id = session_id
    def _load_history(self):
        try:
            if os.path.exists(self.history_file):
                with open(self.history_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    self.scores = data.get("scores", {})
                    self.hall_of_fame = data.get("hall_of_fame", [])
            else:
                self.scores = {}
                self.hall_of_fame = []

            if os.path.exists(self.settings_file):
                with open(self.settings_file, "r", encoding="utf-8") as f:
                    settings = json.load(f)
                    self.ai_interval = settings.get("ai_interval", 5)
                    self.player_count = settings.get("player_count", 4)
                    self.ai_provider = "omnirouter"
                    self.ai_model = settings.get("ai_model", "kr/claude-sonnet-4.5")
                    self.omniroute_url = settings.get("omniroute_url", "http://localhost:20128/v1")
                    self.system_agent_overrides = settings.get("system_agent_overrides", {})
        except Exception as e:
            logger.error(f"Error loading history/settings: {e}")
            self.scores = {}
            self.hall_of_fame = []

    def _save_history(self):
        try:
            with open(self.history_file, "w", encoding="utf-8") as f:
                json.dump({
                    "scores": self.scores,
                    "hall_of_fame": self.hall_of_fame
                }, f, ensure_ascii=False, indent=4)
            
            with open(self.settings_file, "w", encoding="utf-8") as f:
                json.dump({
                    "ai_interval": self.ai_interval,
                    "player_count": self.player_count,
                    "ai_provider": self.ai_provider,
                    "ai_model": self.ai_model,
                    "omniroute_url": self.omniroute_url,
                    "system_agent_overrides": self.system_agent_overrides
                }, f, ensure_ascii=False, indent=4)
        except Exception as e:
            logger.error(f"Error saving history/settings: {e}")

    def _init_map(self):
        logger.info(f"Initialized world map {self.size}x{self.size} (mode={self.game_mode})")

        door_tiles = set()
        for (hx, hy), name in zip(self.house_positions, ["João", "Maria", "Zeca", "Elly"]):
            if name == "João":
                door = (hx, hy + 1)
            elif name == "Maria":
                door = (hx + 1, hy)
            elif name == "Zeca":
                door = (hx, hy - 1)
            else:
                door = (hx - 1, hy)
            if 0 <= door[0] < self.size and 0 <= door[1] < self.size:
                door_tiles.add(door)

        for x in range(self.size):
            for y in range(self.size):
                dist_to_center = (x - self.pond_center_x) ** 2 + (y - self.pond_center_y) ** 2
                if dist_to_center <= self.pond_radius_sq:
                    self.add_entity(f"water_{x}_{y}", {"type": "water", "x": x, "y": y})
                    continue

                if (x, y) in door_tiles:
                    continue

                if random.random() < 0.02:
                    self.add_entity(f"stone_{x}_{y}", {"type": "stone", "x": x, "y": y})
                elif random.random() < 0.01 and dist_to_center > self.tree_min_distance_sq:
                    self.add_entity(f"tree_{x}_{y}", {"type": "tree", "x": x, "y": y, "fruit_stage": 3})

        self.add_entity("house_joao", {"type": "house", "x": self.house_positions[0][0], "y": self.house_positions[0][1], "name": "Casa do João"})
        self.add_entity("house_maria", {"type": "house", "x": self.house_positions[1][0], "y": self.house_positions[1][1], "name": "Casa da Maria"})
        self.add_entity("house_zeca", {"type": "house", "x": self.house_positions[2][0], "y": self.house_positions[2][1], "name": "Casa do Zeca"})
        self.add_entity("house_elly", {"type": "house", "x": self.house_positions[3][0], "y": self.house_positions[3][1], "name": "Casa da Elly"})
        self.add_entity("cemetery_area", {"type": "cemetery", "x": self.cemetery_x, "y": self.cemetery_y, "name": "Cemitério da Ilha"})

        # Spawnar objetos específicos do modo de jogo
        self._spawn_mode_objects()

    def _get_mode_spawn_objects(self) -> list:
        """Retorna lista de objetos extras a spawnar com base no game_mode."""
        margin = max(2, min(4, self.size // 8))
        sz = self.size
        mode = self.game_mode
        objects = []

        if mode in ("gincana",):
            # Checkpoints em 4 cantos mais internos
            positions_cp = [
                (sz // 4, sz // 4),
                (sz * 3 // 4, sz // 4),
                (sz // 4, sz * 3 // 4),
                (sz * 3 // 4, sz * 3 // 4),
            ]
            for i, (cx, cy) in enumerate(positions_cp):
                objects.append({"id": f"checkpoint_{i}", "type": "checkpoint", "x": cx, "y": cy, "name": f"Checkpoint {i+1}", "captured": False})
            objects.append({"id": "artifact_main", "type": "artifact", "x": sz // 2 + 3, "y": sz // 2 - 3, "name": "Artefato Principal", "collected": False})
            objects.append({"id": "delivery_zone", "type": "delivery_marker", "x": margin, "y": sz - margin - 1, "name": "Zona de Entrega"})

        elif mode in ("warfare",):
            # Bases de time
            objects.append({"id": "team_base_a", "type": "team_base", "x": margin + 1, "y": margin + 1, "name": "Base Alpha", "team": "alpha"})
            objects.append({"id": "team_base_b", "type": "team_base", "x": sz - margin - 2, "y": sz - margin - 2, "name": "Base Beta", "team": "beta"})
            # Zona de controle central
            objects.append({"id": "control_zone_center", "type": "control_zone", "x": sz // 2, "y": sz // 2 - 4, "name": "Zona Central", "controlled_by": None, "capture_ticks": 0})
            # Supply crates
            for i, (sx, sy) in enumerate([(sz // 4, sz // 2), (sz * 3 // 4, sz // 2), (sz // 2, sz // 4)]):
                objects.append({"id": f"supply_crate_{i}", "type": "supply_crate", "x": sx, "y": sy, "name": f"Caixote de Suprimentos {i+1}", "loot": ["ammo", "medkit"]})
            # Ammo caches
            for i, (ax, ay) in enumerate([(sz // 3, sz // 3), (sz * 2 // 3, sz // 3), (sz // 3, sz * 2 // 3)]):
                objects.append({"id": f"ammo_cache_{i}", "type": "ammo_cache", "x": ax, "y": ay, "name": f"Depósito de Munição {i+1}", "ammo": 5})
            # Throwables espalhados
            for i in range(6):
                tx, ty = random.randint(margin, sz - margin - 1), random.randint(margin, sz - margin - 1)
                objects.append({"id": f"throwable_{i}", "type": "throwable_stone", "x": tx, "y": ty, "name": "Pedra Arremessável"})
            # Cover
            for i in range(4):
                cx2, cy2 = random.randint(sz // 4, sz * 3 // 4), random.randint(sz // 4, sz * 3 // 4)
                objects.append({"id": f"cover_{i}", "type": "cover", "x": cx2, "y": cy2, "name": f"Abrigo Tático {i+1}"})

        elif mode in ("economy",):
            # Posto de mercado central
            objects.append({"id": "market_post_main", "type": "market_post", "x": sz // 2 + 2, "y": sz // 2 + 2, "name": "Mercado Central", "prices": {"fruit": 1, "water_bottle": 2, "wood": 1}})
            objects.append({"id": "market_post_2", "type": "market_post", "x": sz * 3 // 4, "y": sz // 4, "name": "Mercado Norte", "prices": {"fruit": 2, "water_bottle": 1, "wood": 2}})
            # Storage boxes
            for i, (bx, by) in enumerate([(margin + 2, sz * 2 // 3), (sz - margin - 3, sz // 3)]):
                objects.append({"id": f"storage_box_{i}", "type": "storage_box", "x": bx, "y": by, "name": f"Armazém {i+1}", "inventory": []})
            # Trade orders board
            objects.append({"id": "trade_board", "type": "trade_order", "x": sz // 2 - 3, "y": sz // 2 + 3, "name": "Quadro de Ordens", "orders": []})
            # Contract items
            objects.append({"id": "contract_item_1", "type": "contract_item", "x": sz // 4, "y": sz * 3 // 4, "name": "Contrato de Colheita", "reward": 5, "required": "fruit", "amount": 3})

        elif mode in ("hybrid",):
            # Composto de warfare + economy
            objects.append({"id": "team_base_a", "type": "team_base", "x": margin + 1, "y": margin + 1, "name": "Base Alpha", "team": "alpha"})
            objects.append({"id": "team_base_b", "type": "team_base", "x": sz - margin - 2, "y": sz - margin - 2, "name": "Base Beta", "team": "beta"})
            objects.append({"id": "black_market", "type": "black_market", "x": sz // 2, "y": sz * 3 // 4, "name": "Mercado Negro", "risk": 0.3, "prices": {"ammo": 3, "weapon": 10}})
            objects.append({"id": "sabotage_target_1", "type": "sabotage_target", "x": sz // 4, "y": sz // 2, "name": "Alvo de Sabotagem Alpha", "team_owner": "beta", "hp": 10})
            objects.append({"id": "sabotage_target_2", "type": "sabotage_target", "x": sz * 3 // 4, "y": sz // 2, "name": "Alvo de Sabotagem Beta", "team_owner": "alpha", "hp": 10})
            objects.append({"id": "depot_alpha", "type": "team_inventory_depot", "x": margin + 3, "y": margin + 3, "name": "Depósito Alpha", "team": "alpha", "inventory": []})
            objects.append({"id": "depot_beta", "type": "team_inventory_depot", "x": sz - margin - 4, "y": sz - margin - 4, "name": "Depósito Beta", "team": "beta", "inventory": []})
            for i in range(4):
                tx, ty = random.randint(margin, sz - margin - 1), random.randint(margin, sz - margin - 1)
                objects.append({"id": f"throwable_{i}", "type": "throwable_stone", "x": tx, "y": ty, "name": "Pedra Arremessável"})

        return objects

    def _spawn_mode_objects(self) -> None:
        """Spawna objetos específicos do modo de jogo no mapa atual."""
        mode_objects = self._get_mode_spawn_objects()
        for obj in mode_objects:
            eid = obj.pop("id", f"mode_obj_{len(self.entities)}")
            self.add_entity(eid, obj)
        if mode_objects:
            logger.info(f"Mode '{self.game_mode}': spawned {len(mode_objects)} extra objects.")

    # ── F08 — Catálogo de Missões ─────────────────────────────────────────────

    def _init_missions(self) -> None:
        """Inicializa o catálogo de 8 missões disponíveis."""
        self.mission_catalog = [
            {
                "id": "explore_all_quadrants",
                "name": "Explorador Completo",
                "description": "Visite os 4 quadrantes do mapa.",
                "type": "exploration",
                "target": 4,
                "bonus_score": 15.0,
            },
            {
                "id": "collect_fruits",
                "name": "Coletor de Frutas",
                "description": "Coma ou colete 5 frutas.",
                "type": "collect",
                "target": 5,
                "bonus_score": 10.0,
            },
            {
                "id": "social_butterfly",
                "name": "Borboleta Social",
                "description": "Converse com todos os outros agentes vivos ao menos uma vez.",
                "type": "social",
                "target": 3,
                "bonus_score": 12.0,
            },
            {
                "id": "survival_100_ticks",
                "name": "Sobrevivente",
                "description": "Sobreviva sem morrer por 100 ticks.",
                "type": "survival",
                "target": 100,
                "bonus_score": 20.0,
            },
            {
                "id": "alliance_keeper",
                "name": "Guardião da Aliança",
                "description": "Mantenha uma aliança ativa por 30 ticks.",
                "type": "alliance",
                "target": 30,
                "bonus_score": 18.0,
            },
            {
                "id": "water_provider",
                "name": "Provedor de Água",
                "description": "Beba água 8 vezes.",
                "type": "drink",
                "target": 8,
                "bonus_score": 8.0,
            },
            {
                "id": "bury_2_bodies",
                "name": "Coveiro da Ilha",
                "description": "Enterre 2 corpos no cemitério.",
                "type": "bury",
                "target": 2,
                "bonus_score": 14.0,
            },
            {
                "id": "stay_healthy",
                "name": "Saúde de Ferro",
                "description": "Mantenha HP acima de 80% por 50 ticks consecutivos.",
                "type": "health",
                "target": 50,
                "bonus_score": 16.0,
            },
        ]

    def assign_missions(self) -> None:
        """Atribui missões aleatórias únicas a cada agente na sessão."""
        import random as rn
        available = list(self.mission_catalog)
        rn.shuffle(available)
        for i, agent in enumerate(self.agents):
            mission = available[i % len(available)]
            agent.mission_id = mission["id"]
            agent.mission_state = {"progress": 0, "visited_quadrants": [], "chat_targets": []}
            agent.mission_completed_tick = None
            agent.mission_bonus_score = 0.0
            logger.debug(f"Mission assigned: {agent.name} → {mission['name']}")

    def _tick_missions_f08(self, events: list) -> None:
        """Avança o progresso de missões para cada agente vivo."""
        for agent in self.agents:
            if not agent.is_alive or not agent.mission_id:
                continue
            if agent.mission_completed_tick is not None:
                continue

            mission = next((m for m in self.mission_catalog if m["id"] == agent.mission_id), None)
            if not mission:
                continue

            state = agent.mission_state
            mtype = mission["type"]
            target = mission["target"]
            completed = False

            if mtype == "exploration":
                # Verifica quadrante atual
                qx = 0 if agent.x < self.size // 2 else 1
                qy = 0 if agent.y < self.size // 2 else 1
                q_label = f"{qx}_{qy}"
                visited = state.setdefault("visited_quadrants", [])
                if q_label not in visited:
                    visited.append(q_label)
                state["progress"] = len(visited)
                completed = len(visited) >= target

            elif mtype == "collect":
                state["progress"] = agent.apples_eaten
                completed = agent.apples_eaten >= target

            elif mtype == "social":
                state["progress"] = len(state.get("chat_targets", []))
                completed = state["progress"] >= target

            elif mtype == "survival":
                state["progress"] = min(agent.benchmark.get("ticks_survived", 0), target)
                completed = state["progress"] >= target

            elif mtype == "alliance":
                if agent.alliance is not None:
                    state["progress"] = self.ticks - agent.alliance_since_tick
                else:
                    state["progress"] = 0
                completed = state["progress"] >= target

            elif mtype == "drink":
                state["progress"] = agent.water_drunk
                completed = agent.water_drunk >= target

            elif mtype == "bury":
                state["progress"] = state.get("buried_count", 0)
                completed = state["progress"] >= target

            elif mtype == "health":
                if agent.hp >= 80:
                    state["progress"] = state.get("progress", 0) + 1
                else:
                    state["progress"] = 0
                completed = state["progress"] >= target

            if completed:
                agent.mission_completed_tick = self.ticks
                bonus = mission["bonus_score"]
                agent.mission_bonus_score += bonus
                agent.benchmark["score"] = agent.benchmark.get("score", 0) + bonus
                events.append({
                    "agent_id": agent.id, "name": agent.name,
                    "action": "mission_complete",
                    "event_msg": f"🏅 {agent.name} concluiu a missão '{mission['name']}' (+{bonus} pts)!"
                })
                logger.info(f"Mission complete: {agent.name} → {mission['name']} (+{bonus})")

    # ── F04 — Engine de Eventos Dinâmicos ─────────────────────────────────────

    DYNAMIC_EVENTS = {
        "tempestade": {
            "name": "🌩️ Tempestade",
            "message": "Uma tempestade violenta assola a ilha! Todos perdem HP.",
            "duration": 10,
            "hp_delta": -5,
            "hunger_delta": 0,
            "thirst_delta": -10,  # chuva enche água
        },
        "seca": {
            "name": "🌵 Grande Seca",
            "message": "Uma seca intensa se instala. A sede aumenta rapidamente.",
            "duration": 15,
            "hp_delta": -2,
            "hunger_delta": -3,
            "thirst_delta": -8,
        },
        "suprimentos": {
            "name": "📦 Queda de Suprimentos",
            "message": "Um avião anônimo lança caixotes de suprimentos no centro da ilha!",
            "duration": 5,
            "hp_delta": 0,
            "hunger_delta": 0,
            "thirst_delta": 0,
            "spawn_supplies": True,
        },
        "radio": {
            "name": "📻 Transmissão de Rádio",
            "message": "Um rádio misterioso transmite uma mensagem de fora da ilha: 'Ajuda a caminho... talvez.'",
            "duration": 3,
            "hp_delta": 5,   # Moral boost
            "hunger_delta": 0,
            "thirst_delta": 0,
        },
        "eclipse": {
            "name": "🌑 Eclipse Solar",
            "message": "O sol desaparece! Um eclipse cobre a ilha, desorientando todos.",
            "duration": 8,
            "hp_delta": -1,
            "hunger_delta": -5,
            "thirst_delta": 0,
            "force_night": True,
        },
    }

    def trigger_event(self, event_type: str) -> dict:
        """Dispara um evento global. Retorna o dict do evento."""
        template = self.DYNAMIC_EVENTS.get(event_type)
        if not template:
            return {}
        event = {
            **template,
            "type": event_type,
            "start_tick": self.ticks,
            "end_tick": self.ticks + template["duration"],
        }
        self.active_event = event
        self.event_end_tick = event["end_tick"]
        self.event_history.append(event)
        logger.info(f"F04: Event triggered: {event_type} at tick {self.ticks}")
        return event

    def _tick_events_f04(self, events: list) -> None:
        """Aplica efeitos de evento ativo e sorteia novo evento aleatório."""
        # 1. Limpa evento expirado
        if self.active_event and self.ticks >= self.event_end_tick:
            logger.info(f"F04: Event ended: {self.active_event['type']}")
            self.active_event = None

        # 2. Aplica efeitos do evento ativo em todos os agentes vivos
        if self.active_event:
            ev = self.active_event
            hp_d = ev.get("hp_delta", 0)
            h_d = ev.get("hunger_delta", 0)
            t_d = ev.get("thirst_delta", 0)
            for agent in self.agents:
                if not agent.is_alive:
                    continue
                if hp_d != 0:
                    agent.hp = max(0, min(100, agent.hp + hp_d))
                if h_d != 0:
                    agent.hunger = max(0, min(100, agent.hunger + h_d))
                if t_d != 0:
                    agent.thirst = max(0, min(100, agent.thirst + t_d))

            # Spawn suprimentos se configurado (só no primeiro tick do evento)
            if ev.get("spawn_supplies") and self.ticks == ev["start_tick"]:
                cx, cy = self.size // 2, self.size // 2
                for i in range(3):
                    eid = f"supply_drop_{self.ticks}_{i}"
                    self.add_entity(eid, {"type": "supply_crate", "x": cx + i, "y": cy,
                                          "name": f"Suprimentos Aéreos {i+1}", "loot": ["fruit", "water_bottle"]})

            # Broadcast do evento (só no primeiro tick)
            if self.ticks == ev["start_tick"]:
                events.append({
                    "agent_id": None, "name": None,
                    "action": "event",
                    "event_msg": f"{ev['name']}: {ev['message']}"
                })

        # 3. Sorteia novo evento se nenhum ativo
        if not self.active_event and random.random() < self.event_chance:
            event_type = random.choice(list(self.DYNAMIC_EVENTS.keys()))
            ev = self.trigger_event(event_type)
            if ev:
                events.append({
                    "agent_id": None, "name": None,
                    "action": "event",
                    "event_msg": f"{ev['name']}: {ev['message']}"
                })

    # ── F07 — Reputação Social e Alianças ─────────────────────────────────────

    def form_alliance(self, agent_a_id: str, agent_b_name: str) -> dict:
        """Forma aliança entre agente A e o agente com nome agent_b_name."""
        agent_a = next((a for a in self.agents if a.id == agent_a_id), None)
        agent_b = next((a for a in self.agents if a.name == agent_b_name and a.is_alive), None)
        if not agent_a or not agent_b:
            return {"error": "Agente não encontrado"}
        agent_a.alliance = agent_b.name
        agent_a.alliance_since_tick = self.ticks
        agent_b.alliance = agent_a.name
        agent_b.alliance_since_tick = self.ticks
        agent_a.reputation_score = min(100.0, agent_a.reputation_score + 5.0)
        agent_b.reputation_score = min(100.0, agent_b.reputation_score + 5.0)
        logger.info(f"F07: Alliance formed: {agent_a.name} ↔ {agent_b.name}")
        return {"alliance": f"{agent_a.name} ↔ {agent_b.name}", "since_tick": self.ticks}

    def break_alliance(self, agent_id: str, betrayal: bool = False) -> dict:
        """Quebra aliança do agente. Se betrayal=True, aplica penalidade de reputação."""
        agent = next((a for a in self.agents if a.id == agent_id), None)
        if not agent:
            return {"error": "Agente não encontrado"}
        ally_name = agent.alliance
        # Quebra no aliado também
        ally = next((a for a in self.agents if a.name == ally_name), None)
        if ally:
            ally.alliance = None
        agent.alliance = None
        if betrayal:
            agent.betrayals += 1
            agent.reputation_score = max(-100.0, agent.reputation_score + self.betrayal_penalty)
            logger.info(f"F07: Betrayal by {agent.name}! Reputation: {agent.reputation_score}")
        return {"status": "alliance_broken", "betrayal": betrayal, "agent": agent.name}

    def _tick_reputation_f07(self, events: list) -> None:
        """Aplica bônus de HP para aliados próximos e atualiza reputação por tick."""
        for agent in self.agents:
            if not agent.is_alive or not agent.alliance:
                continue
            ally = next((a for a in self.agents if a.name == agent.alliance and a.is_alive), None)
            if not ally:
                # Aliado morreu — remove aliança automaticamente
                agent.alliance = None
                continue
            # Bônus de HP se aliados estão a menos de 3 tiles
            dist = abs(agent.x - ally.x) + abs(agent.y - ally.y)
            if dist <= 3:
                bonus = self.alliance_bonus_hp_per_tick
                agent.hp = min(100, agent.hp + bonus)
                ally.hp = min(100, ally.hp + bonus)
            # Leve acúmulo de reputação por manter aliança
            agent.reputation_score = min(100.0, agent.reputation_score + 0.05)


    def add_entity(self, entity_id: str, data: dict):
        self.entities[entity_id] = data

    def add_agent(self, agent):
        # Prevent spawn on top of obstacles
        while not self._is_walkable(agent.x, agent.y) or any(a.x == agent.x and a.y == agent.y for a in self.agents):
            agent.x = (agent.x + 1) % self.size
            if agent.x == 0:
                agent.y = (agent.y + 1) % self.size

        self.agents.append(agent)
        self.add_entity(agent.id, {"type": "agent", "x": agent.x, "y": agent.y, "name": agent.name})

    def add_pending_agent(self, agent, delay_ticks):
        spawn_tick = self.ticks + delay_ticks
        self.pending_spawns.append((spawn_tick, agent))
        logger.info(f"Scheduled spawn for {agent.name} at tick {spawn_tick}")

    def remove_agent(self, agent_id: str):
        agent = next((a for a in self.agents if a.id == agent_id), None)
        if agent:
            self.agents.remove(agent)
            self.entities.pop(agent.id, None)
            logger.info(f"Agent {agent.name} removed from world.")
            return True
        return False

    async def tick(self):
        """Advances the world simulation by one unit of time."""
        # 0. Check for auto-reset if game is over (2 min = 120 ticks at 1s/tick)
        if not self.started:
            return []

        self.ticks += 1
        logger.debug(f"World tick {self.ticks}")
        
        events = []

        # Encerramento automático de torneio por tick limite.
        if (
            self.tournament_end_tick is not None
            and self.active_tournament_id is not None
            and self.ticks >= self.tournament_end_tick
            and not self.game_over
        ):
            self.game_over = True
            self.game_over_tick = int(self.ticks)
            events.append({
                "action": "busy",
                "event_msg": f"🏁 Torneio {self.active_tournament_id} encerrado no tick {self.ticks}.",
            })
        
        # 1. Spawn pending agents
        remaining_pending = []
        for spawn_tick, agent in self.pending_spawns:
            if self.ticks >= spawn_tick:
                self.add_agent(agent)
                events.append({"action": "busy", "event_msg": f"{agent.name} CHEGOU NA ILHA! 🏝️✨", "agent_id": agent.id, "name": agent.name})
                logger.info(f"Agent {agent.name} spawned at tick {self.ticks}")
            else:
                remaining_pending.append((spawn_tick, agent))
        self.pending_spawns = remaining_pending

        # 2. Process automatic movements (smooth steps)
        # 3. Update world elements (e.g. day/night cycle, resource respawn)
        if self.ticks % 80 == 0:
            for eid, e in self.entities.items():
                if e.get("type") == "tree" and e.get("fruit_stage", 1) < 3:
                    e["fruit_stage"] += 1
                    logger.debug(f"Tree {eid} grew to stage {e['fruit_stage']}")
        
        # 1.1 Update Agent Vitals (hunger, thirst, hp) every tick
        unburied_body_exists = any(not a.is_alive and not getattr(a, 'is_buried', False) and not getattr(a, 'is_zombie', False) for a in self.agents)
        
        # 1.0 DAY/NIGHT CYCLE - ZOMBIE CONVERSION AT NIGHTFALL
        day_pos = self.ticks % self.DAY_CYCLE
        is_night_now = 80 <= day_pos < 110
        night_just_started = is_night_now and not self._was_night
        
        dawn_just_started = (day_pos >= 110 or day_pos < 80) and self._was_night
        self._was_night = is_night_now
        
        # Daytime Sunlight Disintegration
        if not is_night_now and not self.game_over:
            surviving_agents = []
            for agent in self.agents:
                if getattr(agent, 'is_zombie', False):
                    # Check if zombie is safely inside a house
                    is_safe_inside = False
                    for hx, hy in self.house_positions:
                        if abs(agent.x - hx) + abs(agent.y - hy) <= self.house_shelter_radius:
                            is_safe_inside = True
                            break
                    
                    if not is_safe_inside:
                        events.append({"action": "busy", "event_msg": f"☀️ Aaahh! A luz do sol! {agent.name} virou pó! 💨"})
                        logger.warning(f"ZOMBIE OBLITERATED: {agent.name}")
                        if agent.id in self.entities:
                            del self.entities[agent.id]
                        
                        # SPAWN NEW PLAYER after 10 ticks (10 seconds)
                        if getattr(self, 'agent_class', None):
                            name, personality = self.extra_names[self.spawn_index % len(self.extra_names)]
                            self.spawn_index += 1
                            new_agent = self.agent_class(name, personality, random.randint(0, self.size-1), random.randint(0, self.size-1))
                            # T16+: Aplicar override de perfil se existir
                            pot_id = f"potential_{name.lower()}"
                            if pot_id in self.system_agent_overrides:
                                new_agent.profile_id = self.system_agent_overrides[pot_id]
                            
                            self.add_pending_agent(new_agent, 10)
                            events.append({"action": "busy", "event_msg": f"⏳ UM NOVO SOBREVIVENTE ({name}) CHEGARÁ EM 10 SEGUNDOS para substituir o zumbi!"})

                    else:
                        surviving_agents.append(agent) # Survives in the shadows!
                else:
                    surviving_agents.append(agent)
            self.agents = surviving_agents

        if night_just_started and not self.game_over:
            events.append({"action": "busy", "event_msg": "🌙 A NOITE CAIU NA ILHA! Os mortos podem despertar... 🧟"})
            
        if is_night_now and not self.game_over:
            for agent in self.agents:
                if not agent.is_alive and not getattr(agent, 'is_buried', False) and not getattr(agent, 'is_zombie', False):
                    if getattr(agent, 'carried_by', None) is None:
                        agent.is_zombie = True
                        agent.is_alive = True  # "alive" again as zombie
                        agent.name = f"{agent.name} Zumbi" # Append Zumbi
                        agent.zombie_ticks = 0 # Start survival timer
                        agent.hp = 200  # Tough zombie
                        agent.hunger = 100
                        agent.thirst = 100
                        agent.target_x = None
                        agent.target_y = None
                        events.append({"agent_id": agent.id, "action": "zombie", "name": agent.name, "event_msg": f"🧟 O CORPO LEVANTOU! {agent.name} ESTÁ NA ILHA! CORRAM! 🧟"})
                        logger.warning(f"ZOMBIE: {agent.name} has risen at nightfall!")
                        if agent.id in self.entities:
                            self.entities[agent.id]["is_zombie"] = True
                            self.entities[agent.id]["is_alive"] = True
                            self.entities[agent.id]["name"] = agent.name
        
        if not self.game_over:
            for agent in self.agents:
                if not agent.is_alive:
                    continue
                
                # Update survival benchmark
                if "ticks_survived" not in agent.benchmark:
                    agent.benchmark["ticks_survived"] = 0
                agent.benchmark["ticks_survived"] += 1
                # Skip zombies from normal vitals processing but track their survival
                if getattr(agent, 'is_zombie', False):
                    agent.zombie_ticks = getattr(agent, 'zombie_ticks', 0) + 1
                    if agent.zombie_ticks >= 120: # 1 full cycle (day + night)
                        agent.is_zombie = False
                        if agent.name.endswith(" Zumbi"):
                            agent.name = agent.name[:-6]
                        
                        agent.hp = 100
                        agent.hunger = 50
                        agent.thirst = 50
                        if agent.id in self.entities:
                            self.entities[agent.id]["name"] = agent.name
                            self.entities[agent.id]["is_zombie"] = False
                            
                        events.append({"agent_id": agent.id, "action": "busy", "name": agent.name, "event_msg": f"✨ MILAGRE! Após sobreviver 1 dia como zumbi, {agent.name} se curou! 🧍‍♂️"})
                        logger.info(f"ZOMBIE CURED: {agent.name} survived 120 ticks and is human again.")
                    continue
                    
                # Check Night Cold Damage
                if is_night_now:
                    home_x, home_y = self.house_by_name.get(agent.name, self.house_positions[3])

                    dist_to_home = abs(agent.x - home_x) + abs(agent.y - home_y)
                    if dist_to_home > self.house_shelter_radius:
                        agent.hp -= 2
                        if self.ticks % 5 == 0:
                            events.append({"agent_id": agent.id, "action": "busy", "name": agent.name, "event_msg": "está congelando de frio lá fora! Preciso ir pra casa! 🥶"})

                # The Stench of Death: Panic/Miasma if someone is dead and unburied
                if unburied_body_exists:
                    agent.hp -= random.randint(1, 2) # Penalidade randômica entre 1 e o máx original
                    if self.ticks % 10 == 0:
                        events.append({"agent_id": agent.id, "action": "busy", "name": agent.name, "event_msg": "está passando mal com o miasma! Enterrem o morto rápido! 🤢"})

                # Check if this agent is carrying a body
                is_carrying = any(a.carried_by == agent.id for a in self.agents)
                
                if is_carrying:
                    agent.hunger = 100
                    agent.thirst = 100
                    agent.hp = 100
                    agent.friendship = 100
                    # No decay when carrying a hero/dead body
                else:
                    # Vitals decrease over time (Randomizado conforme pedido)
                    agent.hunger = max(0, agent.hunger - random.randint(1, 2))
                    agent.thirst = max(0, agent.thirst - random.randint(1, 3))
                    
                    # Starvation/Dehydration logic or Recovery
                    if agent.hunger <= 0 or agent.thirst <= 0:
                        agent.hp -= random.randint(1, 3)
                    elif agent.hunger > 70 and agent.thirst > 70:
                        # Regra de cura: se estiver saudável, recupera HP
                        agent.hp += random.randint(1, 2)
                        if agent.hp > 100: agent.hp = 100
                    
                    # Friendship decay: loses 1-2 per tick (social pressure!)
                    agent.friendship = max(0, agent.friendship - random.randint(1, 2))
                
                # Death check
                if agent.hp <= 0:
                    agent.hp = 0
                    agent.is_alive = False
                    agent.hunger = 0
                    agent.thirst = 0
                    agent.death_tick = self.ticks  # Record death time for zombie timer
                    events.append({"agent_id": agent.id, "action": "die", "name": agent.name, "event_msg": "NÃO RESISTIU (Fome/Sede/Frio/Miasma)! 💀"})
                    self._apply_action(agent, {"action": "die"})
                
        # 1.2 Victory Check (Revised: Only ends when EVERYONE is dead)
        alive_agents = [a for a in self.agents if a.is_alive]
        if not self.game_over and len(self.agents) > 0:
            if len(alive_agents) == 0:
                self.game_over = True
                self.winner = None
                self.game_over_tick = int(self.ticks)
                events.append({
                    "action": "draw",
                    "event_msg": "TODOS MORRERAM! A ilha agora é um lugar silencioso... 💀💀"
                })
                logger.info("GAME OVER: Everyone is dead.")

        # 2. Process automatic movement (1 step per tick)
        for agent in self.agents:
            if getattr(agent, "target_x", None) is not None and getattr(agent, "target_y", None) is not None:
                # If already at target or adjacent (dist 1)
                dist_x = abs(agent.x - agent.target_x)
                dist_y = abs(agent.y - agent.target_y)
                
                if dist_x <= 1 and dist_y <= 1:
                    # Arrived or adjacent (target could be a tree/lake)
                    agent.target_x = None
                    agent.target_y = None
                    agent.arrival_tick = self.ticks
                    continue

                # Use BFS to find the next step bypassing obstacles
                dx, dy = self._get_next_step_bfs(agent.x, agent.y, agent.target_x, agent.target_y)
                
                if dx != 0 or dy != 0:
                    new_x = agent.x + dx
                    new_y = agent.y + dy
                    
                    if self._is_walkable(new_x, new_y):
                        agent.x = new_x
                        agent.y = new_y
                    else:
                        # Can't walk, stop
                        agent.target_x = None
                        agent.target_y = None
                        agent.arrival_tick = self.ticks
                else:
                    # No path found
                    logger.warning(f"No path for {agent.name} to {agent.target_x}, {agent.target_y}")
                    agent.target_x = None
                    agent.target_y = None
                    agent.arrival_tick = self.ticks

            # After movement steps, sync entity position
            if agent.id in self.entities:
                self.entities[agent.id]["x"] = agent.x
                self.entities[agent.id]["y"] = agent.y
                
                # Update carried bodies position recursively/immediately
                for other in self.agents:
                    if other.carried_by == agent.id:
                        other.x, other.y = agent.x, agent.y
                        if other.id in self.entities:
                            self.entities[other.id]["x"] = other.x
                            self.entities[other.id]["y"] = other.y
        
        # 2.1 Auto-Interactions by Proximity (Collision Collection)
        for agent in self.agents:
            if agent.is_alive and not getattr(agent, 'is_zombie', False):
                self._check_auto_interactions(agent, events)

        # 2.2 ZOMBIE AI: Removed (Now controlled by Gemini AI)

        # 2.2 Collect events from background AI tasks that finished
        if self.ai_events:
            events.extend(self.ai_events)
            self.ai_events = []
        
        # 3. Trigger AI decisions in background 
        # If ai_interval is 0 (fast mode), trigger all alive agents in parallel. Otherwise, turn-based.
        if self.ai_interval <= 0:
            if self.ticks % 1 == 0 and self.agents and not self.game_over:
                for agent in self.agents:
                    # Skip agents that are still walking or just arrived (1s wait)
                    is_walking = getattr(agent, 'target_x', None) is not None
                    just_arrived = self.ticks <= getattr(agent, 'arrival_tick', -1)
                    if agent.is_alive and not getattr(agent, 'is_remote', False) and not is_walking and not just_arrived and agent.id not in self.thinking_agents:
                        context = self._get_context_for_agent(agent)
                        agent._game_mode = self.game_mode  # Thinker usa para variar prompt
                        asyncio.create_task(self._run_agent_ai_task(agent, context))
        else:
            if self.ticks % self.ai_interval == 0 and self.agents and not self.game_over:
                alive_indices = [i for i, a in enumerate(self.agents) if a.is_alive]
                if alive_indices:
                    turn_num = self.ticks // self.ai_interval
                    idx_in_alive = turn_num % len(alive_indices)
                    agent_index = alive_indices[idx_in_alive]
                    agent = self.agents[agent_index]
                    
                    # Only trigger if not remote AND not already thinking AND not walking AND not just arrived
                    is_walking = getattr(agent, 'target_x', None) is not None
                    just_arrived = self.ticks <= getattr(agent, 'arrival_tick', -1)
                    reason_block = f"remote:{getattr(agent, 'is_remote', False)} thinking:{agent.id in self.thinking_agents} walking:{is_walking} arrived:{just_arrived}"
                    logger.info(f"Eval {agent.name}: {reason_block}")
                    if not getattr(agent, 'is_remote', False) and agent.id not in self.thinking_agents and not is_walking and not just_arrived:
                        logger.info(f"==> DISPATCHING AI TASK para {agent.name}")
                        context = self._get_context_for_agent(agent)
                        agent._game_mode = self.game_mode  # Thinker usa para variar prompt
                        asyncio.create_task(self._run_agent_ai_task(agent, context))

        # ── F04/F07/F08 — Motores de fase 3 ──────────────────────────────────
        self._tick_events_f04(events)
        self._tick_missions_f08(events)
        self._tick_reputation_f07(events)

        # ── F12 — Gincana Engine ──────────────────────────────────────────────
        if self.game_mode == "gincana" and self.gincana.active:
            self.gincana.tick(events)

        # ── F13-F16 — Warfare Engine ──────────────────────────────────────────
        if self.game_mode == "warfare" and self.warfare.active:
            self.warfare.tick(events)

        # ── F10+F17+F18+F19 — Economy Engine ───────────────────────────────
        if self.economy.active:
            self.economy.tick(events)

        # ── F20 — GangWar Engine ─────────────────────────────────────────────
        if self.game_mode in ("gangwar", "hybrid") and self.gangwar.active:
            self.gangwar.tick(events)

        return events


    def _check_auto_interactions(self, agent, events):
        """Processes automatic actions like gathering and picking up items upon collision/proximity."""
        if not agent.is_alive: return

        # 1. Gather fruit (Tree or Floor)
        if len(agent.inventory) < 3:
            for eid, e in list(self.entities.items()):
                # Floor Items
                if e.get("type") == "dropped_fruit" and e.get("x") == agent.x and e.get("y") == agent.y:
                    agent.inventory.append("fruit")
                    self.entities.pop(eid, None)
                    events.append({"action": "busy", "event_msg": f"pegou automaticamente uma maçã do chão! Bolsa ({len(agent.inventory)}/3)", "agent_id": agent.id, "name": agent.name})
                    break 
                # Tree fruit (distance 1)
                elif e.get("type") == "tree" and abs(e.get("x", 0) - agent.x) <= 1 and abs(e.get("y", 0) - agent.y) <= 1:
                    if e.get("fruit_stage", 0) == 3:
                        agent.inventory.append("fruit")
                        e["fruit_stage"] = 1
                        events.append({"action": "busy", "event_msg": f"colheu automaticamente uma maçã da árvore! Bolsa ({len(agent.inventory)}/3)", "agent_id": agent.id, "name": agent.name})
                        break

        # 2. Get Water
        if len(agent.inventory) < 3 and "water_bottle" not in agent.inventory:
            for eid, e in self.entities.items():
                if e.get("type") == "water" and abs(e.get("x", 0) - agent.x) <= 1 and abs(e.get("y", 0) - agent.y) <= 1:
                    agent.inventory.append("water_bottle")
                    events.append({"action": "busy", "event_msg": f"encheu automaticamente a garrafa d'água! Bolsa ({len(agent.inventory)}/3)", "agent_id": agent.id, "name": agent.name})
                    break

        # 3. Pickup Dead Body (if not carrying one and nearby)
        carried_body = next((a for a in self.agents if a.carried_by == agent.id), None)
        if not carried_body and "dead_body" not in agent.inventory and len(agent.inventory) < 3:
            for other in self.agents:
                if not other.is_alive and not getattr(other, 'is_buried', False) and getattr(other, 'carried_by', None) is None:
                    if abs(other.x - agent.x) <= 1 and abs(other.y - agent.y) <= 1:
                        agent.held_item = f"Corpo de {other.name}"
                        other.carried_by = agent.id
                        agent.inventory.append("dead_body")
                        events.append({"action": "busy", "event_msg": f"pegou automaticamente o corpo de {other.name} no colo!", "agent_id": agent.id, "name": agent.name})
                        carried_body = other
                        break

        # 4. Auto Bury if at cemetery
        if carried_body and "dead_body" in agent.inventory:
            if abs(agent.x - self.cemetery_x) <= 2 and abs(agent.y - self.cemetery_y) <= 2:
                carried_body.is_buried = True
                carried_body.carried_by = None
                agent.held_item = None
                agent.inventory.remove("dead_body")
                
                if carried_body in self.agents:
                    self.agents.remove(carried_body)
                self.entities.pop(carried_body.id, None)

                grave_id = f"grave_{carried_body.id}"
                self.add_entity(grave_id, {"type": "dead_agent", "x": agent.x, "y": agent.y, "name": f"Túmulo de {carried_body.name}"})
                events.append({"action": "busy", "event_msg": f"ENTERROU AUTOMATICAMENTE {carried_body.name} no cemitério! Descanse em paz.", "agent_id": agent.id, "name": agent.name})
                
                # Record in Hall of Fame (keep top 3 only based on total interactions)
                record = {
                    "name": carried_body.name,
                    "apples": getattr(carried_body, "apples_eaten", 0),
                    "water": getattr(carried_body, "water_drunk", 0),
                    "chats": getattr(carried_body, "chats_sent", 0),
                    "tick": self.ticks,
                    "score": getattr(carried_body, "apples_eaten", 0) + getattr(carried_body, "water_drunk", 0) + getattr(carried_body, "chats_sent", 0)
                }
                self.hall_of_fame.append(record)
                self.hall_of_fame.sort(key=lambda x: x.get("score", 0), reverse=True)
                self.hall_of_fame = self.hall_of_fame[:3]
                self._save_history()

                # Spawn new agent
                if self.agent_class:
                    name, personality = self.extra_names[self.spawn_index % len(self.extra_names)]
                    self.spawn_index += 1
                    new_agent = self.agent_class(name, personality, random.randint(0, self.size-1), random.randint(0, self.size-1))
                    self.add_pending_agent(new_agent, 10)

    async def _run_agent_ai_task(self, agent, context):
        """Background task to get AI action without blocking the world loop."""
        self.thinking_agents.add(agent.id)
        try:
            if self.ai_decider is not None:
                action_event = await self.ai_decider(agent, context, self.ticks)
            else:
                action_event = await agent.act(context)
            if action_event:
                # Need to synchronize world update
                self._apply_action(agent, action_event)
                if action_event.get("speak"):
                    logger.info(f"[CHAT] {agent.name}: {action_event['speak']}")
                self.ai_events.append(action_event)
        except Exception as e:
            logger.error(f"Error in background AI task for {agent.name}: {e}")
        finally:
            self.thinking_agents.remove(agent.id)

    def _get_context_for_agent(self, agent):
        # Determine what the agent can see based on its x,y
        # Manhattan distance check
        visible_entities = []
        possible_to_gather = False
        possible_to_drink = False
        reachable_resources = []
        
        for eid, e in self.entities.items():
            if eid != agent.id:
                 dist_x = abs(e.get("x", 0) - agent.x)
                 dist_y = abs(e.get("y", 0) - agent.y)
                 dist = dist_x + dist_y
                 
                 if dist <= 12: # Even more sight
                     # Inject real-time status for agents so AI knows who is dead/carried
                     entity_data = e.copy()
                     if e.get("type") == "agent":
                         other_agent = next((a for a in self.agents if a.id == eid), None)
                         if other_agent:
                             # Skip buried agents entirely — they shouldn't appear in the world
                             if getattr(other_agent, "is_buried", False):
                                 continue
                             entity_data["is_alive"] = other_agent.is_alive
                             entity_data["carried_by"] = other_agent.carried_by
                             entity_data["is_buried"] = getattr(other_agent, "is_buried", False)
                     visible_entities.append(entity_data)
                 
                 # Check if can gather right now
                 if e.get("type") == "tree" and dist_x <= 1 and dist_y <= 1:
                     if e.get("fruit_stage") == 3:
                         possible_to_gather = True
                         reachable_resources.append(f"ÁRVORE COM FRUTO em {e['x']},{e['y']}")
                 
                 # Check if can drink right now
                 if e.get("type") == "water" and dist_x <= 1 and dist_y <= 1:
                      possible_to_drink = True
                      reachable_resources.append(f"ÁGUA DO LAGO em {e['x']},{e['y']}")
                 
                 # Check if cemetery is near (only relevant if carrying a body OR someone is dead)
                 carrying_body = any(a.carried_by == agent.id for a in self.agents)
                 unburied_body_exists = any(not a.is_alive and not getattr(a, 'is_buried', False) and not getattr(a, 'is_zombie', False) for a in self.agents)
                 
                 if e.get("type") == "cemetery" and dist_x <= 2 and dist_y <= 2:
                     if carrying_body:
                         reachable_resources.append("ÁREA DO CEMITÉRIO! Você está carregando um corpo e está no local certo. Use a ação 'bury' agora!")
                     elif unburied_body_exists:
                         reachable_resources.append("ÁREA DO CEMITÉRIO. Há corpos não enterrados na ilha! Se você quiser ajudar, vá buscar o corpo primeiro com 'pickup_body' onde ele estiver caído.")
        
        # Check if agent is carrying a body
        carried_body_obj = next((a for a in self.agents if a.carried_by == agent.id), None)
        is_carrying_body = carried_body_obj is not None
        carrying_name = carried_body_obj.name if carried_body_obj else None

        # Day/Night Info
        day_pos = self.ticks % self.DAY_CYCLE
        is_night = 80 <= day_pos < 110

        # F01 — Verificar e expirar human_command
        human_command = getattr(agent, "human_command", None)
        command_expire_tick = getattr(agent, "command_expire_tick", 0)
        if human_command is not None and self.ticks >= command_expire_tick:
            agent.human_command = None
            agent.command_expire_tick = 0
            agent.command_source = "ai"
            human_command = None

        context = {
            "time": self.ticks,
            "is_night": is_night,
            "ai_provider": self.ai_provider,
            "ai_model": self.ai_model,
            "omniroute_url": self.omniroute_url,
            "visible_entities": visible_entities,
            "reachable_now": reachable_resources,
            "can_gather_now": possible_to_gather,
            "can_drink_now": possible_to_drink,
            "inventory": agent.inventory,
            "is_moving_automatically_to": (agent.target_x, agent.target_y) if agent.target_x is not None else None,
            "is_carrying_body": is_carrying_body,
            "carrying_name": carrying_name,
            # F01 — Comando humano injetado no contexto
            "human_command": human_command,
            "command_source": getattr(agent, "command_source", "ai"),
            "game_mode": self.game_mode,
        }

        # ── Injeta info específica do engine ativo ──
        if self.game_mode == "warfare" and self.warfare.active:
            wf_faction = self.warfare.agent_factions.get(agent.id)
            wf_role = self.warfare.agent_roles.get(agent.id)
            context["warfare_info"] = {
                "faction": wf_faction,
                "role": wf_role,
                "alpha_score": self.warfare.faction_scores.get("alpha", 0),
                "beta_score": self.warfare.faction_scores.get("beta", 0),
                "alpha_base_hp": self.warfare.base_hp.get("alpha", 100),
                "beta_base_hp": self.warfare.base_hp.get("beta", 100),
                "territory_holder": self.warfare.territory_holder,
                "territory_ticks": self.warfare.territory_contest_ticks,
                "throws": len(self.warfare.throw_log),
            }
            # Info extra para reachable_now
            enemy_faction = "beta" if wf_faction == "alpha" else "alpha"
            for v in visible_entities:
                if v.get("type") == "agent":
                    v_faction = self.warfare.agent_factions.get(v.get("id", ""))
                    if v_faction:
                        v["faction"] = v_faction
                        v["is_enemy"] = v_faction != wf_faction

        elif self.game_mode == "gincana" and self.gincana.active:
            captured_count = sum(1 for v in self.gincana.checkpoints_captured.values() if v is not None)
            total_cps = len(self.gincana.checkpoints_captured)
            context["gincana_info"] = {
                "checkpoints_status": f"{captured_count}/{total_cps}",
                "artifact_collected": self.gincana.artifact_holder is not None,
                "artifact_holder": self.gincana.artifact_holder,
                "delivery_done": len(self.gincana.deliveries) > 0,
                "remaining_ticks": self.gincana.remaining_ticks(),
                "my_score": self.gincana.gincana_scores.get(agent.id, 0),
            }
            # Marca checkpoints visíveis como capturados ou não
            for v in visible_entities:
                if v.get("type") == "checkpoint":
                    cp_id = next((eid for eid, e in self.entities.items() if e is v), None)
                    if cp_id:
                        v["captured"] = self.gincana.checkpoints_captured.get(cp_id) is not None

        elif self.game_mode == "economy" and self.economy.active:
            context["economy_info"] = {
                "balance": self.economy.coins.get(agent.id, 0),
                "recipes": ", ".join(self.economy.recipes.keys()) if hasattr(self.economy, 'recipes') else "axe, raft, wall, torch, bandage",
                "market_summary": "Vá até um Mercado para ver preços",
                "contracts_count": len(getattr(self.economy, 'active_contracts', [])),
            }

        elif self.game_mode in ("gangwar", "hybrid") and self.gangwar.active:
            gw_gang = self.gangwar.agent_gangs.get(agent.id)
            context["gangwar_info"] = {
                "faction": gw_gang,
                "faction_scores": self.gangwar.gang_scores,
                "depot_alpha_hp": sum(self.gangwar.depots.get("alpha", {}).values()),
                "depot_beta_hp": sum(self.gangwar.depots.get("beta", {}).values()),
                "bm_prices": self.gangwar.bm_prices,
            }

        return context

        
    def _is_walkable(self, x, y):
        # Verifica se as coordenadas estão dentro dos limites do mapa e não contêm obstáculos
        if not (0 <= x < self.size and 0 <= y < self.size):
            return False
        for eid, e in self.entities.items():
            if e.get("x") == x and e.get("y") == y:
                etype = e.get("type")
                if etype in ["tree", "stone", "water", "agent"]:
                    # Spacial case: carried agents don't block
                    if etype == "agent":
                        agent_obj = next((a for a in self.agents if a.id == eid), None)
                        # Dead bodies or carried bodies don't block movement
                        if agent_obj and (agent_obj.carried_by or not agent_obj.is_alive):
                            continue
                    return False
        return True

    def _get_next_step_bfs(self, start_x, start_y, target_x, target_y):
        """BFS pathfinding to find the first step towards a target, avoiding obstacles."""
        queue = collections.deque([(start_x, start_y, [])])
        visited = set([(start_x, start_y)])
        
        while queue:
            curr_x, curr_y, path = queue.popleft()
            
            # If it's the exact target, we arrived
            if curr_x == target_x and curr_y == target_y:
                if path: return path[0]
                return (0, 0)
            
            # If the target is NOT walkable (like a tree), then being adjacent is enough
            if not self._is_walkable(target_x, target_y):
                if abs(curr_x - target_x) <= 1 and abs(curr_y - target_y) <= 1:
                    if path: return path[0]
                    return (0, 0)

            # 8 directions
            directions = [(1,0),(-1,0),(0,1),(0,-1),(1,1),(1,-1),(-1,1),(-1,-1)]
            for dx, dy in directions:
                nx, ny = curr_x + dx, curr_y + dy
                
                if (nx, ny) not in visited and 0 <= nx < self.size and 0 <= ny < self.size:
                    # Obstacle check
                    if self._is_walkable(nx, ny):
                        visited.add((nx, ny))
                        new_path = path + [(dx, dy)]
                        queue.append((nx, ny, new_path))
                    elif nx == target_x and ny == target_y:
                        # Target can be an obstacle but we want to be adjacent
                        return path[0] if path else (dx, dy)
        return (0, 0)

    def _apply_action(self, agent, action_event):
        # Any new manual action (except talk/wait) cancels automatic movement
        act_type = action_event.get("action")
        # Actions that DON'T cancel automatic movement (target_x/y)
        if act_type not in ["wait", "busy", "speak"]:
            agent.target_x = None
            agent.target_y = None
            
        if act_type == "move":
            dx, dy = action_event.get("dx", 0), action_event.get("dy", 0)
            
            new_x = agent.x + dx
            new_y = agent.y + dy
            
            if self._is_walkable(new_x, new_y):
                agent.x = new_x
                agent.y = new_y
                # update entity representation
                if agent.id in self.entities:
                    self.entities[agent.id]["x"] = agent.x
                    self.entities[agent.id]["y"] = agent.y
                
                # update carried body position
                for other in self.agents:
                    if other.carried_by == agent.id:
                        other.x, other.y = agent.x, agent.y
                        if other.id in self.entities:
                            self.entities[other.id]["x"] = other.x
                            self.entities[other.id]["y"] = other.y
            else:
                 action_event["event_msg"] = "bateu de cara com um obstáculo!"
                 logger.debug(f"{agent.name} bumped into an obstacle at {new_x}, {new_y}")
                 
        elif act_type == "move_to":
            agent.target_x = action_event.get("target_x")
            agent.target_y = action_event.get("target_y")
            
            if agent.target_x is not None and agent.target_y is not None:
                 action_event["event_msg"] = f"planejou trilhar caminho até as coordenadas {agent.target_x}, {agent.target_y}!"
                 logger.info(f"{agent.name} planned a route to {agent.target_x}, {agent.target_y}")
                 
        elif act_type == "gather":
            if len(agent.inventory) >= 3:
                 action_event["event_msg"] = f"tentou colher mas a bolsa está LOTADA (3/3)!"
            else:
                 # Check for trees nearby
                 gathered = False
                 for eid, e in self.entities.items():
                     if e.get("type") == "tree":
                         if abs(e["x"] - agent.x) <= 1 and abs(e["y"] - agent.y) <= 1:
                             if e.get("fruit_stage", 0) == 3:
                                 agent.inventory.append("fruit")
                                 e["fruit_stage"] = 1 # Reset
                                 action_event["event_msg"] = f"colheu uma fruta madura com sucesso! Bolsa: ({len(agent.inventory)}/3)"
                                 logger.info(f"{agent.name} gathered fruit from {eid}!")
                                 gathered = True
                                 break 
                 if not gathered:
                      action_event["event_msg"] = "tentou colher, mas não tem árvore madura ao alcance (distância 1)."

        elif act_type == "pick_up":
            if len(agent.inventory) >= 3:
                 action_event["event_msg"] = "tentou pegar do chão, mas a bolsa está cheia!"
            else:
                 picked_from_floor = None
                 for eid, e in self.entities.items():
                     if e.get("type") == "dropped_fruit" and e["x"] == agent.x and e["y"] == agent.y:
                         picked_from_floor = eid
                         break
                 
                 if picked_from_floor:
                     agent.inventory.append("fruit")
                     del self.entities[picked_from_floor]
                     action_event["event_msg"] = f"pegou uma fruta que estava nos seus pés! Bolsa: ({len(agent.inventory)}/3)"
                     logger.info(f"{agent.name} picked up item from floor")
                 else:
                     action_event["event_msg"] = "tentou pegar algo, mas o chão está vazio aqui."

        elif act_type == "eat":
            if "fruit" in agent.inventory:
                 agent.hunger = min(100, agent.hunger + 80)
                 agent.apples_eaten += 1
                 agent.inventory.remove("fruit")
                 action_event["event_msg"] = f"comeu a fruta! Fome: {agent.hunger}/100"
                 logger.info(f"{agent.name} ate a fruit. Hunger now {agent.hunger}")
            else:
                 action_event["event_msg"] = "TENTOU COMER mas não tinha fruta na bolsa!"

        elif act_type == "fill_bottle":
            if len(agent.inventory) >= 3:
                 action_event["event_msg"] = "bolsa cheia! Não cabe a garrafa d'água."
            else:
                 # Check for water nearby
                 can_fill = False
                 for eid, e in self.entities.items():
                     if e.get("type") == "water":
                         if abs(e["x"] - agent.x) <= 1 and abs(e["y"] - agent.y) <= 1:
                             can_fill = True
                             break
                 if can_fill:
                     agent.inventory.append("water_bottle")
                     action_event["event_msg"] = "encheu uma garrafa com água do lago! 🍶"
                     logger.info(f"{agent.name} filled a water bottle")
                 else:
                      action_event["event_msg"] = "TENTOU PEGAR ÁGUA mas está longe do lago."

        elif act_type == "drink":
            if "water_bottle" in agent.inventory:
                 agent.thirst = 100
                 agent.water_drunk += 1
                 agent.inventory.remove("water_bottle")
                 action_event["event_msg"] = f"bebeu a água da garrafa! Sede: {agent.thirst}/100"
                 logger.info(f"{agent.name} drank water. Thirst now {agent.thirst}")
            else:
                 action_event["event_msg"] = "TENTOU BEBER mas não tem garrafa d'água na bolsa! Vá ao lago e use 'fill_bottle'."

        elif act_type == "die":
            action_event["event_msg"] = f"MORREU E CAIU NO CHÃO! 💀. Alguém precisa levá-lo ao cemitério ({self.cemetery_x},{self.cemetery_y})!"
            logger.warning(f"DEATH: {agent.name} is down at {agent.x},{agent.y}")
            # Ensure entity is marked as dead immediately for AI visibility
            if agent.id in self.entities:
                self.entities[agent.id]["is_alive"] = False
            # Se estava carregando alguém, soltar o corpo
            carried_body = next((a for a in self.agents if a.carried_by == agent.id), None)
            if carried_body:
                carried_body.carried_by = None
                carried_body.x, carried_body.y = agent.x, agent.y
                # Update entity position for the dropped body
                if carried_body.id in self.entities:
                    self.entities[carried_body.id]["x"] = carried_body.x
                    self.entities[carried_body.id]["y"] = carried_body.y
                action_event["event_msg"] += f" O corpo de {carried_body.name} que estava na bolsa também caiu!"
                logger.info(f"Body of {carried_body.name} dropped at {agent.x},{agent.y} because carrier {agent.name} died.")

        elif act_type == "attack":
            # Zombie attack logic
            target_name = action_event.get("target_name")
            target = next((a for a in self.agents if a.name == target_name and a.is_alive), None)
            
            if target and abs(target.x - agent.x) <= 1 and abs(target.y - agent.y) <= 1:
                damage = 20 # Zumbis batem forte
                target.hp -= damage
                action_event["event_msg"] = f"ATACOU {target.name}! (-{damage} HP) 🩸"
                logger.warning(f"{agent.name} (Zombie) attacked {target.name}")
                
                if target.hp <= 0:
                    target.hp = 0
                    target.is_alive = False
                    target.death_tick = self.ticks
                    action_event["event_msg"] += f" {target.name} FOI ABATIDO PELO ZUMBI!"
                    self._apply_action(target, {"action": "die"})
            else:
                action_event["event_msg"] = "tentou atacar mas errou o bote! (Ninguém por perto)"

        elif act_type == "pickup_body":
            # Check for dead agents nearby
            found_body = None
            for other in self.agents:
                if not other.is_alive and not other.is_buried and other.carried_by is None:
                    if abs(other.x - agent.x) <= 1 and abs(other.y - agent.y) <= 1:
                        found_body = other
                        break
            
            if found_body:
                agent.held_item = f"Corpo de {found_body.name}"
                found_body.carried_by = agent.id
                # Add to inventory to show in UIbag
                if "dead_body" not in agent.inventory:
                    agent.inventory.append("dead_body")
                action_event["event_msg"] = f"pegou o {found_body.name} no colo para levar ao cemitério! O corpo apareceu na bolsa."
            else:
                # Silêncio para evitar spam no chat global
                logger.debug(f"{agent.name} tried to pickup_body but none nearby.")

        elif act_type == "bury":
            # Check if carrying a body and at cemetery area (radius 2 for tolerance)
            carried_body = next((a for a in self.agents if a.carried_by == agent.id), None)
            if carried_body:
                if abs(agent.x - self.cemetery_x) <= 2 and abs(agent.y - self.cemetery_y) <= 2:
                    carried_body.is_buried = True
                    carried_body.carried_by = None
                    agent.held_item = None
                    # Remove from inventory
                    if "dead_body" in agent.inventory:
                        agent.inventory.remove("dead_body")
                    
                    # Remove the body from the map and world state
                    if carried_body in self.agents:
                        self.agents.remove(carried_body)
                    self.entities.pop(carried_body.id, None)

                    # Create grave entity
                    grave_id = f"grave_{carried_body.id}"
                    self.add_entity(grave_id, {"type": "dead_agent", "x": agent.x, "y": agent.y, "name": f"Túmulo de {carried_body.name}"})
                    action_event["event_msg"] = f"Enterrou {carried_body.name} com honras! Recorde de vida: 🍎{carried_body.apples_eaten} | 💧{carried_body.water_drunk} | 🗣️{carried_body.chats_sent}"
                    
                    # Record in Hall of Fame (Keep top 3 based on total score)
                    record = {
                        "name": carried_body.name,
                        "apples": carried_body.apples_eaten,
                        "water": carried_body.water_drunk,
                        "chats": carried_body.chats_sent,
                        "tick": self.ticks,
                        "score": carried_body.apples_eaten + carried_body.water_drunk + carried_body.chats_sent
                    }
                    self.hall_of_fame.append(record)
                    self.hall_of_fame.sort(key=lambda x: x.get("score", 0), reverse=True)
                    # Keep only top 3 records
                    self.hall_of_fame = self.hall_of_fame[:3]
                    self._save_history()
                    
                    # SPAWN NEW PLAYER after 10 ticks (10 seconds)
                    if self.agent_class:
                        name, personality = self.extra_names[self.spawn_index % len(self.extra_names)]
                        self.spawn_index += 1
                        new_agent = self.agent_class(name, personality, random.randint(0, self.size-1), random.randint(0, self.size-1))
                        self.add_pending_agent(new_agent, 10)
                        action_event["event_msg"] += f" | UM NOVO SOBREVIVENTE ({name}) CHEGARÁ EM 10 SEGUNDOS!"
                else:
                    action_event["event_msg"] = f"TENTOU ENTERRAR mas não está no Cemitério ({self.cemetery_x},{self.cemetery_y})!"
            else:
                action_event["event_msg"] = "TENTOU ENTERRAR mas não está carregando ninguém."

        # Friendship boost: 
        msg = action_event.get("speak", "").strip()
        if msg != "":
            # Bigger boost if they choose specifically to bond ("speak" action)
            # Smaller boost (+5) if they just comment while doing other things
            boost = 40 if act_type == "speak" else 5
            
            # Meritocracy: Only the speaker gets the friendship points!
            if agent.is_alive:
                agent.friendship = min(100, agent.friendship + boost)
                agent.chats_sent += 1
            # Atualiza percepção relacional do alvo quando houver target_name explícito
            target_name = action_event.get("target_name", "").strip()
            if target_name:
                target = next((a for a in self.agents if a.name == target_name), None)
                if target and hasattr(agent, "agent_memory"):
                    agent.agent_memory.update_relation(
                        target_name,
                        opinion_delta=0.05 if act_type == "speak" else 0.02,
                        tick=self.ticks,
                        note=f"Interação social em T{self.ticks}",
                    )
            logger.info(f"Social boost: {agent.name} socialized (Action: {act_type}), friendship +{boost}.")
        # ... other actions like talk etc don't necessarily update world position

        # Ataques pioram a percepção relacional entre atacante e alvo
        if act_type == "attack":
            target_name = action_event.get("target_name", "").strip()
            if target_name and hasattr(agent, "agent_memory"):
                agent.agent_memory.update_relation(
                    target_name,
                    opinion_delta=-0.25,
                    tick=self.ticks,
                    note=f"Ataque em T{self.ticks}",
                )

    def get_state(self):
        """Returns the full current state of the world to be sent to frontend."""
        # Refresh agent state in entities map
        for agent in self.agents:
             if agent.id in self.entities:
                 # If being carried, update position to the carrier's position
                 if agent.carried_by and agent.carried_by in self.entities:
                     carrier = next((a for a in self.agents if a.id == agent.carried_by), None)
                     if carrier:
                         agent.x, agent.y = carrier.x, carrier.y

                 self.entities[agent.id].update({
                     "x": agent.x,
                     "y": agent.y,
                     "hunger": agent.hunger,
                     "thirst": getattr(agent, "thirst", 0),
                     "hp": agent.hp,
                     "friendship": getattr(agent, "friendship", 50),
                     "is_alive": agent.is_alive,
                     "inventory": agent.inventory,
                     "apples_eaten": getattr(agent, "apples_eaten", 0),
                     "water_drunk": getattr(agent, "water_drunk", 0),
                     "chats_sent": getattr(agent, "chats_sent", 0),
                     "is_zombie": getattr(agent, "is_zombie", False),
                     "human_command": getattr(agent, "human_command", None),
                     "command_source": getattr(agent, "command_source", "ai"),
                 })

                 
        next_agent_name = None
        if self.ai_interval > 0:
            ticks_to_next_turn = self.ai_interval - (self.ticks % self.ai_interval)
        else:
            ticks_to_next_turn = 0
        
        if self.agents and self.ai_interval > 0:
            next_think_tick = self.ticks + ticks_to_next_turn
            next_agent_index = (next_think_tick // self.ai_interval) % len(self.agents)
            next_agent_name = self.agents[next_agent_index].name

        reset_countdown = None
        if self.game_over and self.game_over_tick is not None:
            reset_countdown = max(0, 120 - (self.ticks - self.game_over_tick))

        return {
            "size": self.size,
            "ticks": self.ticks,
            "started": self.started,
            "session_id": self.session_id,
            "entities": self.entities,
            "agents": [
                {
                    "id": a.id,
                    "name": a.name,
                    "hp": a.hp,
                    "is_alive": a.is_alive,
                    "is_zombie": getattr(a, "is_zombie", False),
                    "tokens_used": getattr(a, "tokens_used", 0),
                    "token_budget": getattr(a, "token_budget", 10000),
                    "cooldown_remaining": max(
                        0,
                        int(getattr(a, "cooldown_ticks", 0))
                        - (self.ticks - int(getattr(a, "last_thought_tick", -99))),
                    ),
                    "profile_id": getattr(a, "profile_id", "claude-kiro"),
                    "owner_id": getattr(a, "owner_id", ""),
                    "benchmark": getattr(a, "benchmark", {}),
                    "cost_usd": float(getattr(a, "benchmark", {}).get("cost_usd", 0.0)),
                }
                for a in self.agents
            ],
            "next_agent": next_agent_name,
            "ticks_to_next_turn": ticks_to_next_turn,
            "game_over": self.game_over,
            "winner_id": self.winner.id if self.winner else None,
            "scores": self.scores,
            "hall_of_fame": self.hall_of_fame,
            "reset_countdown": reset_countdown,
            "ai_interval": self.ai_interval,
            "player_count": self.player_count,
            "ai_provider": self.ai_provider,
            "ai_model": self.ai_model,
            "omniroute_url": self.omniroute_url,
            "day_cycle": self.ticks % self.DAY_CYCLE,
            "is_night": 80 <= (self.ticks % self.DAY_CYCLE) < 110,
            "game_mode": self.game_mode,
            # F04 — Evento ativo
            "active_event": self.active_event,
            "event_history_count": len(self.event_history),
            # F08 — Catálogo de missões
            "mission_catalog_count": len(self.mission_catalog),
            # F12 — Gincana
            "gincana": self.gincana.get_state() if self.game_mode == "gincana" else None,
            # F13-F16 — Warfare
            "warfare": self.warfare.get_state() if self.game_mode == "warfare" else None,
            # F10+F17+F18+F19 — Economy (sempre exposto independente de modo)
            "economy": self.economy.get_state(),
            # F20 — Guerra de Gangues
            "gangwar": self.gangwar.get_state() if self.game_mode in ("gangwar", "hybrid") else None,
        }

    def reset_agents(self, AgentClass, player_count=None):
        """Reset agents to their starting positions and states."""
        if player_count is not None:
            self.player_count = int(player_count)
            self._save_history()
        
        player_count = self.player_count
        self.agent_class = AgentClass
        self.agents = []
        self.entities = {}
        self.pending_spawns = []
        self.spawn_index = 0
        
        # Possible Initial Squad
        # Possible Initial Squad with fixed IDs
        squad = [
            AgentClass("João", "Pragmático. Você foca em encontrar comida, árvores de frutos e não morrer de fome. Só pensa na sobrevivência.", self.house_positions[0][0], self.house_positions[0][1], agent_id="sys_joao"),
            AgentClass("Maria", "Arquiteta. Você quer construir abrigos e pontes. Gosta de coletar madeira e pedra, e falar sobre plantas de casas.", self.house_positions[1][0], self.house_positions[1][1], agent_id="sys_maria"),
            AgentClass("Zeca", "Zeca é um surfista relaxado. Ele gosta de ficar perto do lago, beber água e conversar sobre a vibe da ilha.", self.house_positions[2][0], self.house_positions[2][1], agent_id="sys_zeca"),
            AgentClass("Elly", "Elly é uma cozinheira. Ela quer juntar o máximo de frutas possível e organizar um banquete.", self.house_positions[3][0], self.house_positions[3][1], agent_id="sys_elly")
        ]

        # Atribui um perfil de IA diferente para cada personagem default
        # Todos usam o mesmo endpoint OmniRoute — só o modelo muda.
        _default_profiles = ["claude-kiro", "kimi-thinking", "kimi-groq", "claude-haiku"]
        for i, agent in enumerate(squad):
            # Prioridade para o override persistente
            saved_profile = self.system_agent_overrides.get(agent.id)
            if saved_profile:
                agent.profile_id = saved_profile
            else:
                agent.profile_id = _default_profiles[i % len(_default_profiles)]

        # Add only the first N players selected
        for i in range(min(player_count, len(squad))):
            self.add_agent(squad[i])

        self.ticks = 0
        self.game_over = False
        self.winner = None
        self.game_over_tick = None
        self.tournament_end_tick = None
        self.active_tournament_id = None
        self._init_map()
        # Auto-start do engine do modo ativo; desativar engines de modos anteriores
        self.gincana.active = False
        self.warfare.active = False
        self.economy.active = False
        self.gangwar.active = False
        if self.game_mode == "gincana":
            self.gincana.start()
        elif self.game_mode == "warfare":
            self.warfare.start()
        elif self.game_mode == "economy":
            self.economy.start()
        elif self.game_mode in ("gangwar", "hybrid"):
            self.gangwar.start()
        # Economy sempre roda em paralelo (crafting disponível em qualquer modo)
        if self.game_mode != "economy":
            self.economy.start()
        logger.info(f"World reset triggered with house spawns. Mode engine '{self.game_mode}' auto-started.")
